spring:
  datasource:
    url: jdbc:mysql://baf039976bddf6:8359e953@us-cdbr-east-06.cleardb.net/heroku_fe2fb1b8a2b856a?reconnect=true
    username: baf039976bddf6
    password: 8359e953
  jpa:
    show: true
    hibernate:
      dd-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect