spring:
  datasource:
    url: jdbc:mysql://sql358.main-hosting.eu:3306/u598362885_testcrud
    username: u598362885_testspring
    password: Test-spring23
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true
    main:
      allow-bean-definition-overriding: true