spring:
  datasource:
    url: jdbc:mysql://b40057afa0ae7d:4859f11b@us-cdbr-east-06.cleardb.net/heroku_b61631dce8bba82
    username: b40057afa0ae7d
    password: 4859f11b
  jpa:
    show: true
    hibernate:
      dd-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect